### ISSUE TITLE
Descriptive statistics for sub-samples

### ISSUE THREAD

**Issue by ttome2016** [jasp-stats/jasp-desktop#1518]
I've been looking around JASP for quite some time and I could not find a solution for this, so I'm guessing that this feature is not included in the software. If that is the case, I would like to request it, for I consider it to be very useful, both for me and the people working with me:

It should be possible to get descriptive statistics (mean, median, SD and so forth) from sub-samples within a sample. For instance, in a database I have individual income data. I would like to be able to ask JASP to calculate those descriptive statistics, using one of the database fields as a separating factor - for example, "Sex", thus resulting in mean incomes being calculated for male and female respondents separately.

I believe this would be a very important element and one that I can't figure out why it is still not included in the package.

JASP has been one of the most interesting statpack projects coming up recently and I've been introducing it to my students. Having this possibility would be great!

Thank you very much!

**Comment by EJWagenmakers** [comment]
@vankesteren 
Thanks. Yes, this would be useful. We only just added the boxplot functionality which allows "split by", but we need to carry that through for all of the descriptives.

**Comment by ttome2016** [comment]
Thanks for your reply!

I noticed the slipt boxplot option, which made the lacking of the rest of the features stand out even more for me. I truly hope that this is soon implemented. I'm currently responsible for an introductory graduate course on statistics and I wanted to do it completely on JASP, but it is still not possible, due to some of the lacking features.
Histograms would also be welcome, especially if one could control the "breakpoints" between categories. But the current feature request would be MUCH more important.

Congrats on the wonderful work, though!

**Comment by ttome2016** [comment]
Your feedback rate is incredible. I was just telling my students this morning that I had made a feature request over here and relaying your answer. They were very excited to hear that in the near future JASP will be having this feature, as a consequence of their needs.

This was, possibly, the most effective way of demonstrating to them the power of Open Source software. I'll be looking forward for the following versions of JASP and I'll try to contribute by suggesting additional features (I am unfortunately useless when it comes to programming skills), in the hope that next year I can teach my stats course using exclusively JASP.

Once again, many thanks!

**Comment by EJWagenmakers** [comment]
:-)
Thanks. We really appreciate the suggestions.
E.J.

**Comment by ttome2016** [comment]
I've just noticed you guys added this to version 0.8.1.0 milestone, which is apparently due by october 25th. Does this mean you will be releasing that new version on that day, including the requested feature?
:-)

**Comment by EJWagenmakers** [comment]
What, we have a date for 0.8.1?? That's news to me :-) This year?? :-) 
And who knows, Erik-Jan created the "split by" really quickly but I'm not sure how much work it is to overhaul the entire Descriptives. Sometimes a change that appears minor can be a lot of work to do well.
E.J.

**Comment by ttome2016** [comment]
Well, that is what your milestones page states - maybe it's just a typo...

No worries, just my enthusiasm getting me carried away!

**Comment by FransMeerhoff** [comment]
Hi @ttome2016 

You were right about that typo... Sorry to  say but there will be a release 0.8.0.1 before the 0.8.1.0. The 0.8.0.1 will mostly contain bug fixes and some other small enhancements, and will be there quite soon. For the  0.8.1 is no release date is planned yet. Unfortunately an incorrect due date was added to the 0.8.1 version. Sorry for that.

Regards 
Frans Meerhoff

**Comment by ttome2016** [comment]
OK, I guessed that was the case. I'll be looking forward to this (and all the other added features which I'm sure you guys will have for that version)!

All best!

**Comment by boutinb** [comment]
@vankesteren: is this implemented?

**Comment by vankesteren** [comment]
No. For now it remains only in the split plots. A descriptives overhaul would be required for this which is why we implemented it like that as an intermediate solution. Per-analysis _data filtering_ is on our roadmap for the near future, which will (partially) solve this issue.

**Comment by ttome2016** [comment]
That is unfortunate. As I've said earlier on this thread, my plan would be to have my introductory stats course based exclusively on JASP, but that is still not possible due to, mainly, two features lacking:

Split descriptives and histograms with the hability to define breakpoints for the categories.

I understand you guys do your best on this project, but I would like to underline its importance - this is the only free statpack that I know of that is also light, simple to use and that can work right out of a flash drive. This makes it a major candidate for educational purposes and, most of all, in contexts where resources are scarce. I truly hope that this becomes more complete in the near future, for I see myself preparing under-grad and grad students on a 100% JASP-diet (if the needed features are available).

**Comment by EJWagenmakers** [comment]
I agree that a descriptives overhaul might be needed, because plotting the
data is a key activity. If we allow the user to edit the plots as well,
then this would be great too. Definitely something to keep in mind when
we've finished our current set of priorities.
Cheers,
E.J.

********************************************
Eric-Jan Wagenmakers
Department of Psychological Methods, room G 0.29
University of Amsterdam, Nieuwe Achtergracht 129B
Letter: PO Box 15906, 1001 NK Amsterdam
Parcel: Valckenierstraat 59,  1018 XE Amsterdam

Web: ejwagenmakers.com
Book: bayesmodels.com
Stats: jasp-stats.org
Email: EJ.Wagenmakers@gmail.com
Cell: (+31) 6 45626624

“Man follows only phantoms.”
Pierre-Simon Laplace, last words
********************************************

**Comment by EJWagenmakers** [comment]
Point taken, and this is something we'll consider doing soon. Of course, we
also need to add logistic regression, a chi-square test, etc :-) Enough
work for the next few years! But our team will be expanding a lot so we
will be able to add more functionality quickly.

Cheers,
E.J.

********************************************
Eric-Jan Wagenmakers
Department of Psychological Methods, room G 0.29
University of Amsterdam, Nieuwe Achtergracht 129B
Letter: PO Box 15906, 1001 NK Amsterdam
Parcel: Valckenierstraat 59,  1018 XE Amsterdam

Web: ejwagenmakers.com
Book: bayesmodels.com
Stats: jasp-stats.org
Email: EJ.Wagenmakers@gmail.com
Cell: (+31) 6 45626624

“Man follows only phantoms.”
Pierre-Simon Laplace, last words
********************************************

**Comment by ttome2016** [comment]
Well, chi square is already available, even if on a very simple iteration.
BTW, is Fisher exact test on your future planos?

Em 12/04/2017 9:55 da manhã, "EJWagenmakers" <notifications@github.com>
escreveu:

**Comment by EJWagenmakers** [comment]
Hmm yes, I'm not sure why that test is missing.
E.J.

********************************************
Eric-Jan Wagenmakers
Department of Psychological Methods, room G 0.29
University of Amsterdam, Nieuwe Achtergracht 129B
Letter: PO Box 15906, 1001 NK Amsterdam
Parcel: Valckenierstraat 59,  1018 XE Amsterdam

Web: ejwagenmakers.com
Book: bayesmodels.com
Stats: jasp-stats.org
Email: EJ.Wagenmakers@gmail.com
Cell: (+31) 6 45626624

“Man follows only phantoms.”
Pierre-Simon Laplace, last words
********************************************
