### ISSUE TITLE
(BUG) Summary stats - Correlation BF error JASP 0.8.0.1 OS X (& REQUEST)

### ISSUE THREAD

**Issue by sinisalakic** [jasp-stats/jasp-desktop#1667]
Hi there,

first of all, I'd like to thank you for a great missionary job you are doing with JASP. I use it mainly to introduce Bayes to the 1st year psychology students (University of Banja Luka, Bosnia&Herzegovina) and it is a perfect tool for such a purpose; and I also spread the news about JASP wherever possible.

As for request, I wonder if you might incorporate calculations of polychoric correlations and factor analysis based on them. Could you also think of including McDonald's omega coefficients in addition to alphas when it comes to reliability options? 

Finally, it is a tiny bug that I found: when computing BFs in the summary stats module, they are calculated correctly, but Prior&Posterior plot presents them the other way around (01 instead of 10 and vv; this happens only when you change Bayes Factor in the menu to BF01). 

![sumcorr_bferror](https://cloud.githubusercontent.com/assets/26273348/23698737/f4c72ff4-03ec-11e7-84f7-515d9170e674.png)

Best,
Siniša

**Comment by boutinb** [comment]
@sinisalakic By coincidence, we have just released a new version today which fix the Sumstat bug you mention, and which implements the McDonald's omega coefficients! It could not be a better timing!
This version also implements data & label editing. We will add more videos on the site to explain how it works, but you may already try it.
For your request for calculations of polychoric correlations, we are also busy to implement it. Coming soon...

**Comment by sinisalakic** [comment]
Wow, incredible timing!

Thanks

**Comment by sinisalakic** [comment]
Unfortunately, the bug is still there...Version 0.8.1.0

Please, choose BF01 and Additional info...

**Comment by boutinb** [comment]
@sinisalakic Sorry, I check it wrongly, a bit too enthousiast with the new release. 
@akashrajkn Can you fix this problem?

**Comment by akashrajkn** [comment]
@boutinb I'll look into it
