### ISSUE TITLE
Feature request: Simple effects in Anova

### ISSUE THREAD

**Issue by ManuelGimenes** [jasp-stats/jasp-desktop#1957]
* Enhancement: add simple effects analyses in Anova
* Purpose: would it be possible to include in JASP the possibility to test simple effects in Anova, please ? traditionnaly, when an interaction is significant (between two factors for example), it is interesting to describe this interaction by using simple effects (testing the effect of factor 1 for each condition of factor 2).

**Comment by EJWagenmakers** [comment]
I strongly endorse this feature request. One of my friends kept an old Mac in his basement for 10 years, only because it had an antique stats program that did this analysis. Apparently it is very useful but few programs easily deliver it. Can we add this, please?

**Comment by Emoll9** [comment]
I would like to add my support for this request. This functionality was recently introduced in the GAMLj module for Jamovi, and I would love see it matched by JASP.

**Comment by hcp4715** [comment]
I add my support too.

**Comment by akashrajkn** [comment]
Fixed in #2223

**Comment by hcp4715** [comment]
I found that the simple effect for repeated measures ANOVA is still missing

**Comment by EJWagenmakers** [comment]
A Christmas present for @JohnnyDoorn? :-)

**Comment by ross2006** [comment]
I found that the simple effect for repeated measures ANOVA is still missing. YES！It's been a year since the first request.I wanna cry!

**Comment by ross2006** [comment]
I found that the simple effect for repeated measures ANOVA is still missing. YES！It's been a year since the first request.I wanna cry! PLEASE PLEASE PLEASE!

**Comment by EJWagenmakers** [comment]
@JohnnyDoorn -- people *really* seem to want this feature badly, can you take a look?

**Comment by JohnnyDoorn** [comment]
It's at the top of my list - it should be in the next release!

**Comment by stjep** [comment]
Perhaps I'm being dense, but I can't see a way to implement a simple effect analysis on an interaction term on an interaction term, which is what this feature request is after.

**Comment by EJWagenmakers** [comment]
@JohnnyDoorn, can you comment?

**Comment by JohnnyDoorn** [comment]
Hi @stjep 
The feature request is about investigating an interaction effect in an anova, by looking at the main effect of one variable, conditioned on levels of a different factor (which can then be conditioned on a third factor). You can use that to get more insight into an interaction effect. 
Adding a second conditioning variable provides more insight into a three-way interaction effect: it shows if there is a main effect of a variable, conditioned on a second variable, conditioned on a third variable.
These features have been implemented in JASP, so it should be possible to get this working.
Perhaps you can tell me what kind of data you have and what research question? 
Kind regards
Johnny

**Comment by stjep** [comment]
@JohnnyDoorn, okay, I think I see where it is implemented (and that I was just being dense). The Simple Main Effects section of the ANOVA specification is what I'm after? With the *Simple effect factor* being what is tested and the *Moderator factor* levels held constant?

Say I have two factors, A and B. Factor A has 2levels. Factor B has 7 levels. The interaction of these two factors is significant. Depending on my theoretical motivation, I may be interested in knowing if there is a difference in Factor B when A is held constant, or vice versa.

Doing a Simple Main Effect of factor A gives me:
```
B1    A1-A2
B2    A1-A2
B3    A1-A2
B4    A1-A2
B5    A1-A2
B6    A1-A2
B7    A1-A2
```

(I'm assuming it is A1-A2, the output is not very clear. The output also does not correct for the number of comparisons here, which seems odd given that this is implemented very nicely for *Post Hoc Tests*.)

This answers the question if there is a difference between the levels of A at each of the levels of B. Cool.

Doing the reverse in JASP, asking for *Simple Main Effects* of B gives me:

```
A1    B1-B2-B3-B4-B5-B6-B7
A2    B1-B2-B3-B4-B5-B6-B7
```

While this is useful if we're seeing a difference on the levels of A, it doesn't complete the picture. The COMPARE command in SPSS would break this down into t-tests and give me the difference between B1 and the other levels of B, one at a time, for A1 and A2. Is there a way to achieve this in JASP? The SPSS syntax, for reference, is:

/EMMEANS = TABLES(A*B) COMPARE(B) ADJ(Bonferroni)

SPSS would then provide a table where for each level of A, every combination of the levels of B is contrasted. At A1, we should see B1 contrasted against B2, B3, B4, B5, B6 and B7, followed by B2 contrasted against B1, B3, B4, B5, B6, B7, and so on. The ADJ command should, in theory, adjust these using a Bonferroni correction, but this actually doesn't seem to happen because the *p* values are the same as they would be if the adjustment was specified as LSD (aka, no correction), but that's one of many issues with SPSS.

What I'm interested in is this implementation of simple effects testing, which is what I assumed OP was after also, but I could be wrong on that one.

IBM's specification for the COMPARE command, and a guide to doing simple effects in SPSS are below:

https://www-01.ibm.com/support/docview.wss?uid=swg21475404

https://stats.idre.ucla.edu/spss/faq/how-can-i-do-tests-of-simple-main-effects-in-spss/

**Comment by Emoll9** [comment]
@stjep It looks like what you're after is _comparison of individual cell means_. In your example above, the tests of A within B and B within A constitute what is formally considered simple-effects analysis, so the JASP feature indeed does what it claims to do. 

I agree, however, that it would be useful to also implement the option to follow up significant simple effects with individual cell-means comparisons. This would complete the left path of the following procedure recommended in Maxwell, S. E., Delaney, H. D., & Kelley, K. (2018). _Designing experiments and analyzing data_. New York: Routledge (p. 344). (Note that they recommend using the same Bonferroni-corrected alpha when testing the simple effect _and_ when comparing the individual cell means.)

![image](https://user-images.githubusercontent.com/33546762/44031795-70a85b3e-9f05-11e8-9578-4badf5805481.png)

**Comment by JohnnyDoorn** [comment]
Hi @stjep & @Emoll9 
Thank you for your feedback. This would indeed be a handy follow-up feature to have. 
For now, you can achieve this with JASP through the filtering function: simply select just one level of the moderator factor (for instance, filter out all observations of A that are not 1), and then perform an ANOVA and posthoc test, then repeat for other levels of A. Although I have to say I am not sure how it would work with the p-value adjustments (i.e., whether those that JASP provides will be suitable for this way of doing simple effects post hoc analysis).
Also, when you do this, you will notice that the ANOVA sum of squares using the filtering method will be equal to the sum of squares reported in the simple main effects table, because the simple main effects is basically just a conditional ANOVA. However, the F statistic (and therefore p-value) is different, because a different denominator is used in the calculation. This is the way that the method accounts for simple effects, and it is therefore not necessary to correct the p-value for multiple comparisons. If you wish, you can still apply something straightforward such as the Bonferoni correction though.
I will put the feature on our todo list, for instance by adding a tickbox for "posthoc tests" in the simple main effects menu. 
Kind regards,
Johnny

**Comment by stjep** [comment]
@Emoll9, you are correct that what I am after is the individual cell means, and thanks for the cool flowchart. Going to have check that book out as it seems useful. Although, I wouldn't recommend a Bonferroni correction, especially not on the cell means, given it's severity. I think a Bonferroni-Holm is a better compromise, but there's no way to get out from behind Bonferroni's shadow.

@JohnnyDoorn, there are a lot of ways to test the cell means, but as long as they are more difficult than tacking a few bits of syntax onto a SPSS command it'll be hard to persuade people to switch from SPSS to JASP if they can't make it all the way through an analysis flowchart like the one @Emoll9 shared. Looking forward to seeing this implemented in the future, and thanks for even considering it.
