### ISSUE TITLE
Network analysis breakdown

### ISSUE THREAD

**Issue by JASPUSER09990** [jasp-stats/jasp-desktop#2512]
## Template for bug reports

* JASP version: Version 0.8.6
* OS name and version: Windows 7 Enterprise SP1
* Analysis: Network analysis
* Steps to reproduce: Network analysis --> Select 25 variables as Dependent variables --> Click "Network plot" --> Add a binary variable to "split by". Then, a box coming out saying "JASPEngine.exe has stopped working". The whole programme stopped. 
This mistake message also occures when I want to save the plot as pdf file. 
This mistake message also occures when I change the estimator.
I guess this breakdown is due to too many DVs.

**Comment by vandenman** [comment]
Hi, I cannot reproduce the error using the attached example dataset. Could you perhaps test if the error also occurs with the attached dataset?
[BigFiveInventory.zip](https://github.com/jasp-stats/jasp-desktop/files/1983304/BigFiveInventory.zip)

**Comment by JASPUSER09990** [comment]
![untitled](https://user-images.githubusercontent.com/39075740/39751645-219b7cc4-52fc-11e8-8dd6-ed5e1c915b34.jpg)
It happens again as the picture shows. I found it's ok if you put DVs in and keep it unchanged. But if you add some covariate or change another setting such as estimators, then, the software stops.

**Comment by AlexanderLyNL** [comment]
I've tried the JASP file and ran it on our beta version. This seems to be fixed. Please reopen if the problem reappears in the new version that is due to be released soon.

**Comment by JASPUSER09990** [comment]
![screenpic](https://user-images.githubusercontent.com/39075740/41816381-3345a64e-77c7-11e8-9d08-9b5493fddef3.jpg)
Tested in JASP 0.9.0.0 (the same computer and system). The problem exists when saving the plot as eps file (see attached picture).

**Comment by JASPUSER09990** [comment]
Could you please reopen this issue as I have already re-checked it in the latest version and the problem exists as well? Thanks.

**Comment by leaesthetics** [comment]
I have just the same problem with the newest version when trying to save the plot as a pdf. Saving as the default format works, but then the resolution is too bad. Thanks

**Comment by AlexanderLyNL** [comment]
Hi leaestethics,

We've identified the problem with saving plots and have fixed this for our next release. If wouldn't be too much trouble, could you please help out and test this issue once our prerelease is ready? 

Cheers,
Alexander

**Comment by JASPUSER09990** [comment]
@AlexanderLyNL Hey, Alexander. Looking forward to the new release. And I will also let you know how it goes. Thanks.

**Comment by leaesthetics** [comment]
@AlexanderLyNL Hi Alexander, thank you so much. Of course I will test it. Cheers!

**Comment by AlexanderLyNL** [comment]
@JASPUSER09990 and @leaesthetics This issue should be fixed. Could you please try one of our experimental builds? 

Mac:
https://static.jasp-stats.org/JASP-0.9.1.0-Nightly-03-10-2018.dmg

Windows:
https://static.jasp-stats.org/JASP-0.9.1.0-Setup-Nightly-03-10-2018(64).exe
https://static.jasp-stats.org/JASP-0.9.1.0-Setup-Nightly-03-10-2018(32).exe

Please refresh before saving.

Cheers,
Alexander

**Comment by JASPUSER09990** [comment]
@AlexanderLyNL Dear Alexander, I have just tried the latest version using the BigFiveInventory.csv. The problem still exists. Please check it using the following steps:

1. Load BigFiveInventory.csv
2. Open Network windows
3. Drag A1-O5 to DV box
4. Click "Network plot" under Plots
5. Select gender variable to 'Split by' box

Then, you will see this information:
![20181011125931](https://user-images.githubusercontent.com/39075740/46778360-b279ac00-cd56-11e8-99a3-5b4f007bc8c5.jpg)

**Comment by AlexanderLyNL** [comment]
Hi @JASPUSER09990, 

I cannot reproduce this on my workstation. In addition, I can also save the plot as a pdf. Can you tell me whether you have admin access on your workstation? Once we have a preinstalled version of JASP-0.9.1.0-Setup-Nightly-03-10-2018(64), I'll send you another link, and hopefully that'll fix it. 

Cheers,
Alexander

**Comment by JASPUSER09990** [comment]
@AlexanderLyNL I have admin access on this PC. I just re-performed the steps using right click 'run as admin". The result is the same.
If I run step 1-4, and save the plot as pdf, then the same error inf. appears. However, If I reduce the number of var in step 3 (e.g., A1-C4), I can save the plot as pdf.
Thanks.
