### ISSUE TITLE
Copying a whole analysis with images in it, doesn't work

### ISSUE THREAD

**Issue by jonathon-love** [jasp-stats/jasp-desktop#792]
under windows, the following is output at the console:

    libpng warning: iCCP: known incorrect sRGB profile

<img width="500" alt="screen shot 2015-07-11 at 12 49 45 pm" src="https://cloud.githubusercontent.com/assets/3240247/8634552/5b0559bc-27cb-11e5-884a-4b2ff13ee010.png">

**Comment by dropmann** [comment]
Fixed. It doesn't effect the 0.7.1 Beta.

**Comment by jonathon-love** [comment]
i still have this problem when running from the development branch.

**Comment by dropmann** [comment]
yep, i have yet to commit.
